apiVersion: v1
kind: Service
metadata:
  name: file-checker
  namespace: file-checker-app
spec:
  selector:
    app: file-checker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

